# Generated by Django 4.0.2 on 2022-02-19 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('patronymic', models.CharField(max_length=32)),
                ('specialization', models.IntegerField(choices=[(0, 'Кардіолог'), (1, 'Отоларинголог'), (2, 'Терапевт'), (3, 'Офтальмолог'), (4, 'Невролог'), (5, 'Хірург'), (6, 'Онколог')])),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('patronymic', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='recordtodoctor',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.doctor'),
        ),
        migrations.AlterField(
            model_name='recordtodoctor',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reception.patient'),
        ),
    ]
