# Generated by Django 4.0.2 on 2022-02-19 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0003_doctorday_doctortimestamp_doctor_end_work_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorday',
            name='doctor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reception.doctor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctortimestamp',
            name='doctor_day',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='reception.doctorday'),
            preserve_default=False,
        ),
    ]
