# Generated by Django 4.0.2 on 2022-02-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0005_doctortimestamp_end_time_stamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='recordtodoctor',
            name='medical_services',
            field=models.ManyToManyField(to='reception.MedicalService'),
        ),
    ]
