# Generated by Django 4.0.2 on 2022-02-19 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0006_medicalservice_recordtodoctor_medical_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recordtodoctor',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='recordtodoctor',
            name='medical_services',
            field=models.ManyToManyField(blank=True, null=True, to='reception.MedicalService'),
        ),
    ]
