# Generated by Django 4.0.2 on 2022-02-19 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reception', '0007_alter_recordtodoctor_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='admission_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
