CARDIOLOGIST = 0
OTOLARYNGOLOGIST = 1
THERAPIST = 2
OPTHALMOLOGIST = 3
NEUROLOGIST = 4
SURGEON = 5
ONCOLOGIST = 6

SPECIALIZATION_CHOICES = (
    (CARDIOLOGIST, 'Кардіолог'),
    (OTOLARYNGOLOGIST, 'Отоларинголог'),
    (THERAPIST, 'Терапевт'),
    (OPTHALMOLOGIST, 'Офтальмолог'),
    (NEUROLOGIST, 'Невролог'),
    (SURGEON, 'Хірург'),
    (ONCOLOGIST, 'Онколог'),
)